### PR TITLE
Update scales.py

### PR DESCRIPTION
**Pull request by kwadwo00**
Added RELATIVE_KEY_DICT in pychord/pychord/constants/
Building functionality for relative chord progressions by numbers.

### CODE REVIEW

**Comment by yuma-m** [comment]
Thank you for your pull-request.

I want to know the usage of `RELATIVE_KEY_DICT`.
Would you kindly add or show an example to use this?

**Comment by kwadwo00** [comment]
I have updated the parser file to be able to do this. I can add an additional pull request for the parser changes.

from pychord import Chord
chord = '3sus2$Cmin'
chord = Chord(chord)
print(chord.components())

The sus2 chord of the third note of the C minor scale. This is backward compatible as well. There appear to be no problems handling standard chord inputs.

Also, if you want a different symbol than a dollar sign to denote the scale, let me know.

**Comment by yuma-m** [comment]
Thank you for your reply.
I understood what you want to do.

How about adding a new class method and parsing it like this?

```py
class Chord(object):
    @classmethod
    def from_note_index(cls, note, quality, scale):
        if not 1 <= note <= 10:
            raise ValueError("Invalid note {}".format(note))
        relative_key = RELATIVE_KEY_DICT[scale[-3:]][note - 1]
        root_num = NOTE_VAL_DICT[scale[:-3]]
        root = VAL_NOTE_DICT[root_num + relative_key % 12][0]
        return cls("{}{}".format(root, quality))
```

This also works as same as yours.

```py
>>> chord = Chord.from_note_index(note=3, quality="sus2", scale="Cmin")
>>> print(chord.components())
['Eb', 'F', 'Bb']
```

**Comment by kwadwo00** [comment]
Very clean implementation. Looks good.

**Pull request merged**
