### PR TITLE
Test (and correct) that all "M" and "maj" qualities are synonyms for each other

### PR DESCRIPTION
**Pull request by nickurak**
The existence of, for example Cmaj13, may suggest the existence of CM13, which currently doesn't exist

RFC: Is this sort of an idea helpful? I got slightly tripped up on a Cmaj13 existing, where CM13 didn't, whereas (generally) the qualities module has capital-M for major (mostly with "maj" synonyms).

I'm not really sure if this is an area of music-theory where ambiguity/inconsistency creeps in, and a blanket expectation like this might not make sense.

No pressure, with the latest quality-iterating and quality-adding functionality, it's easy for me to patch in quality types like this in contexts where I expect them.

### CODE REVIEW

**Comment by nickurak** [comment]
(BTW, I'm aware the tests don't pass yet :smile: but if this proposal of expecting synonyms of qualities to show up, I'd look at addressing those failures).

**Comment by yuma-m** [comment]
Hi @nickurak, sorry for the late reply.
Your idea looks useful. Could you kindly update it to pass the test cases?
Thank you.

**Comment by nickurak** [comment]
Thanks @yuma-m for having a look. I've added the missing equivalent qualities, and the tests pass now. Ready to merge.

Future work could be simplifying the creation/management of qualities, such that synonyms are always done right, but I'm not taking that on right now anyways.

**Comment by yuma-m** [comment]
Thanks @nickurak, looks good to me.

**Pull request merged**
